name: Anrick Portfolio
favicon: null
layout_spectrum: 0.8002231786958873
typography_spectrum: 0.8924785919953138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.55586620233953
  lightness: 0.18651199201121926
  saturation: 0.5916007382329553
  rhythmicContrast: 0.3436405872926116
purpose: []
